version: '3.8'
services:    
  strapi:        
    build: 
      context: .
      dockerfile: ./node/Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:            
      - "1337:1337"
      - "8000:8000"
    networks:
      - strapi-project

networks:
  strapi-project: