FROM node:lts

WORKDIR /app

COPY ./strapi/package.json ./

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install -g npm@latest

RUN yarn install

COPY strapi ./

EXPOSE 1337 8000

CMD ["yarn", "develop", "--watch-admin"]